spring:
  application:
    name: user
  profiles:
    active:
      - db
#      - db-url-home
      - db-url-company
      - mybatis
#      - nacos-url-home
      - nacos-url-company
      - dubbo3-p
server:
  port: 8024