spring:
  application:
    name: goods
  profiles:
    active:
      - db
#      - db-url-home
#      - nacos-url-home
      - db-url-company
      - nacos-url-company
      - mybatis
      - dubbo-p
      - seata-common
      - seata
server:
  port: 8025