spring:
  application:
    name: goods
  profiles:
    active:
      - db
      #      - db-url-home
      - db-url-company
      - mybatis
      #      - nacos-url-home
      - nacos-url-company
      - dubbo3-p
server:
  port: 8025