dubbo:
  registry:
    timeout: 2000
    use-as-config-center: false
    use-as-metadata-center: false
  protocol:
    #    -1:会分配一个没有被占用的端口，默认是20880
    port: -1
    name: dubbo
    threads: 200
  application:
    logger: slf4j
    name: goods
    qos-enable: true
    qos-port: 22223