server:
  port: 8025

#通过web暴露端点监控actuator,还可以通过jmx暴露
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"

#mybatis配置文件
# classpath*:需要遍历所有的classpath
mybatis:
  mapper-locations: classpath:com/shopping/user/mapper/*Mapper.xml