#bootstrap会覆盖active的设置
spring:
  profiles:
    active: dev
  cloud:
    stream:
      bindings:
        order:
#          绑定producer的时候没有group
          destination: order
          producer:
#            默认是true
            autoStartup: true
          binder: rabbit
