# mysql
#spring:
#  datasource:
#    url: 在 application-db-url 中
#    username: 在 application-db-url 中
#    password: 在 application-db-url 中


# tk.mybatis需要扫描
mapper:
  mappers:
    - com.shopping.common.db.CommonMapper

mybatis-plus:
  global-config:
    db-config:
      capital-mode: true

#mybatis配置文件
# classpath*:需要遍历所有的classpath
mybatis:
  mapper-locations: classpath:com/shopping/*/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.shopping.order.dao: debug