#bootstrap会覆盖active的设置
spring:
  profiles:
    active: dev
  application:
    name: zuul

management:
  endpoint:
    routes:
      enabled: true
    filters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

ribbon:
  ReadTimeout: 4000