spring:
  #  rabbitmq
  rabbitmq:
    host: 192.168.70.169
    port: 5672
    username: admin
    password: 444944
    virtual-host: GHost

    # 确认消息已发送到交换机
    publisher-confirms: true
    # 消息发送失败后返回
    publisher-returns: true

    listener:
      # 默认配置是simple
      type: simple
      simple:
        # 手动ack Acknowledge mode of container. auto none
        acknowledge-mode: manual
        # Maximum number of unacknowledged messages that can be outstanding at each consumer.
        prefetch: 3
  cloud:
    stream:
      #      如果有一个binder的话,就不需要设置
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
#          如果配置了spring.rabbitmq,会覆盖下面的配置
          environment:
            spring:
              rabbitmq:
                host: 192.168.70.169
                port: 5672
                username: admin
                password: 444944
                virtual-host: GHost
        rabbit1:
          type: rabbit
          defaultCandidate: false
          environment:
            spring:
              rabbitmq:
                host: 192.168.70.169
                port: 5672
                username: admin
                password: 444944
                virtual-host: GHost
      bindings:
        order:
          destination: order
          binder: rabbit
          #          绑定producer的时候没有group
          group: myOrderQueue
          producer:
            #            默认是true
            autoStartup: true
          conumer:
            concurrency: 3
        cart:
          #          如果没有指定routing key,会使用默认的 #
          binder: rabbit1
          destination: order
          group: myCartQueue
      # rabbit的扩展配置 RabbitExtendedBindingProperties
      rabbit:
        bindings:
          order:
            consumer:
              bindingRoutingKey: order
          cart:
            consumer:
              bindingRoutingKey: cart
mqtt:
  allow:
    anonymous: false
  auth:
    username: admin
    password: 444944
  set:
    clean:
      session: true
  broker: tcp://192.168.70.169:1883
  qos: 1