spring:
  rabbitmq:
    host: 192.168.70.167
    port: 5672
    username: admin
    password: public
    #    virtual-host: GHost
    virtual-host: /

    # 确认消息已发送到交换机
    publisher-confirms: true
    # 消息发送失败后返回
    publisher-returns: true

    listener:
      # 默认配置是simple
      type: simple
      simple:
        # 手动ack Acknowledge mode of container. auto none
        acknowledge-mode: manual
        # Maximum number of unacknowledged messages that can be outstanding at each consumer.
        prefetch: 3