# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 下单
POST http://localhost:8027/cart/checkout
Content-Type: application/json

{
  "userId": 1,
  "amount": 2001,
  "goodsItems": [
    {
      "goodsId": 1,
      "quantity": 1
    }
  ],
  "rollback": true
}

### 获取商品详情
GET http://localhost:8027/cart/goods/1