# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### flowControl/sayHello
GET http://localhost:8030/flowControl/sayHello?name=han
Accept: application/json

### flowControl/sayBye
GET http://localhost:8030/flowControl/sayBye?name=han
Accept: application/json
