spring:
  application:
    name: demo
    # spring 静态资源扫描路径
  resources:
    static-locations: classpath:/static/
  profiles:
    active:
      - dev
#      - redis-standalone
mybatisx:
  mappers: hanshaoohua