spring:
  redis:
    #    host: 在 application-redis-url中
    #    port: 在 application-redis-url中
    #    password: 在 application-redis-url中
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 60000
    timeout: 5000
