# mysql
spring:
  datasource:
    #      #    homePC docker
    url: jdbc:mysql://192.168.0.124:3306/sp_user?allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 242492