server:
  port: 8030
spring:
  main:
    allow-circular-references: true
  application:
    name: demo
  profiles:
    active:
      - db
      - db-url-company
      - mybatis
      - dubbo-c
      - nacos-url-company
      - cache
      - redis-url-company
      - sentinel
#      - sharding-rwsplitting-company
#通过web暴露端点监控actuator,还可以通过jmx暴露
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"

#logging:
#  level:
#    com.shopping.demo.dao: debug
#debug: false
