spring:
  shardingsphere:
    datasource:
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3316/shopping?serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3326/shopping?serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
      names: master,slave0
    masterslave:
      name: ms
      masterDataSourceName: master
      slaveDataSourceNames: slave0
      load-balance-algorithm-type: round_robin
    props:
      sql:
        show: true